#horizontal grid step in semitones
h_step: 1
#vertical grid step in semitones; this results in a configuration
#where the major 3rd is directly above
v_step: 4

#"center" velocity used in sensitivity calculation (0-127)
vel_center: 80
#root midi note
root: 48
#amount to offset (right/up) the root note
x_offset: 0
y_offset: -1
#can be a single integer indicating the positive octave offset per pad,
#or a list of relative octave offsets per pad
pad_octave_offsets: [-1, 1]
#output midi device to send events to
output_device: "loopMIDI Port 3"
#midi device to listen to; the Launchpad will light up as if it were playing notes heard from this device
# feedback_device: "lunchbox"
#enable the visualizer (requires pygame, see README)
visualizer: true
#list of colors per note, starting at C if un-transposed
colors:
  - "#22FF44" #C
  - "#000000"
  - "#222222" #D
  - "#000000"
  - "#222222" #E
  - "#226644" #F
  - "#000000"
  - "#226644" #G
  - "#000000"
  - "#222222" #A
  - "#000000"
  - "#222222" #B
#split mode, if non-0, offset the right half of the LP by this many octaves
split_mode: 0

#TODO: test manual device listing
autodetect: false
in_devices: ["MIDIIN2 (LPX MIDI) 4", "MIDIIN4 (LPX MIDI) 6"]
out_devices: ["MIDIOUT2 (LPX MIDI) 5", "MIDIOUT4 (LPX MIDI) 7"]
