#horizontal grid step in semitones
h_step: 1
#vertical grid step in semitones; this results in a configuration
#where the major 3rd is directly above
v_step: 4
#velocity scaling; lower values "squish" the velocity space towards max velocity
vel_scale: 0.5
#root midi note
root: 50 #TODO: used to be 48, but increased for higher TET
#amount to offset (right/up) the root note
x_offset: 0
y_offset: -1
#can be a single integer indicating the positive octave offset per pad,
#or a list of relative octave offsets per pad
pad_octave_offsets: [-1, 1]
#output midi device to send events to
output_device: "loopMIDI Port 1"
#midi device to listen to; the Launchpad will light up as if it were playing notes heard from this device
# feedback_device: "lunchbox"
#enable the visualizer (requires pygame, see README)
visualizer: true
#list of colors per note, starting at C if un-transposed
colors:
  - "#00FF00" #C
  - "#000000"
  - "#222222" #D
  - "#000000"
  - "#222222" #E
  - "#ff6600" #F
  - "#000000"
  - "#0000FF" #G
  - "#000000"
  - "#222222" #A
  - "#000000"
  - "#222222" #B

#split mode, if non-0, offset the right half of the LP by this many octaves
split_mode: 0

#TODO: test manual device listing
autodetect: false
in_devices: ["MIDIIN2 (LPX MIDI) 2", "MIDIIN4 (LPX MIDI) 4"]
out_devices: ["MIDIOUT2 (LPX MIDI) 3", "MIDIOUT4 (LPX MIDI) 5"]
